### ISSUE TITLE
Handle no Internet connection while streaming audio 🎧

### ISSUE THREAD

**Issue by YajanaRao** [YajanaRao/react-native-audio#9]
Need to handle No internet connection scenario in case of Streaming online songs.

**Comment by YajanaRao** [comment]
If internet is not connected while loading the data source, No internet connection toast will be given when we try to play the song. If user turns on internet after loading the data source, well it is not handled yet 😒😒😒😒😒😒😒.

**Comment by wachiranduati** [comment]
Hi, I would really like to work on this if that's okay with you?

**Comment by YajanaRao** [comment]
Sure.

**Comment by wachiranduati** [comment]
Sorry I hadn't noticed this was react native...thanks though
